# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190918_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-upvotes',)},
        ),
    ]
